default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  prepared_statements: false

development:
  <<: *default
  database: stream_development

test:
  <<: *default
  database: stream_test

profile:
  <<: *default
  database: stream_development
